/**
 * Create circle types
 *
 * @version 0.0.1
 * @author Arshdeep Singh (https://github.com/Singh-Arshdeep)
 */

export const CREATE_CIRCLE_REQUEST = 'CREATE_CIRCLE_REQUEST';
export const CREATE_CIRCLE_SUCCESS = 'CREATE_CIRCLE_SUCCESS';
export const CREATE_CIRCLE_FAILURE = 'CREATE_CIRCLE_FAILURE';
export const GET_CIRCLE_TYPES_AND_PLUGINS_REQUEST =
  'GET_CIRCLE_TYPES_AND_PLUGINS_REQUEST';
export const GET_CIRCLE_TYPES_AND_PLUGINS_SUCCESS =
  'GET_CIRCLE_TYPES_AND_PLUGINS_SUCCESS';
export const GET_CIRCLE_TYPES_AND_PLUGINS_FAILURE =
  'GET_CIRCLE_TYPES_AND_PLUGINS_FAILURE';
