/**
 * Expense Manager plugin types
 *
 * @version 0.0.1
 * @author Arshdeep Singh (https://github.com/Singh-Arshdeep)
 */

export const EXPENSE_MANAGER_REQUEST = 'EXPENSE_MANAGER_REQUEST';

//Load Categories
export const EXPENSE_MANAGER_LOAD_CATEGORIES_SUCCESS =
  'EXPENSE_MANAGER_LOAD_CATEGORIES_SUCCESS';
export const EXPENSE_MANAGER_LOAD_CATEGORIES_Failure =
  'EXPENSE_MANAGER_LOAD_CATEGORIES_FAILURE';
//Load Bills
export const EXPENSE_MANAGER_LOAD_BILLS_SUCCESS =
  'EXPENSE_MANAGER_LOAD_BILLS_SUCCESS';
export const EXPENSE_MANAGER_LOAD_BILLS_FAILURE =
  'EXPENSE_MANAGER_LOAD_BILLS_FAILURE';
//Add Bill
export const EXPENSE_MANAGER_ADD_BILL_SUCCESS =
  'EXPENSE_MANAGER_ADD_BILL_SUCCESS';
export const EXPENSE_MANAGER_ADD_BILL_FAILURE =
  'EXPENSE_MANAGER_ADD_BILL_FAILURE';

export const EXPENSE_MANAGER_FAILURE = 'EXPENSE_MANAGER_FAILURE';
